# Goldmark 配置
goldmark:
  renderer:
    # 允许在 Markdown 中使用原始 HTML
    unsafe: true

# Hugo Chroma 代码高亮配置
highlight:
  codeFences: true
  guessSyntax: false
  lineNos: true
  lineNumbersInTable: true
  noClasses: false