main:
  - name: "首页"
    pageRef: "/"
    weight: 10
  - name: "文章"
    pageRef: "/archives/"
    weight: 20
  - name: "想法"
    pageRef: "/ideas/"
    weight: 30
  - name: "关于"
    pageRef: "/about/"
    weight: 40
  - name: "RSS"
    url: "/rss.xml"
    weight: 50